<a href="https://colab.research.google.com/github/TiffanyHizon/Linear_Algebra_58051/blob/main/Laboratory%20Activity%206/LinAlg_58051_Hizon_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TASK 1**

Create a function named mat_desc() that througouhly describes a matrix, it should:


1.   Displays the shape, size, and rank of the matrix.
2.   Displays whether the matrix is square or non-square.
3. Displays whether the matrix is an empty matrix.
4. Displays if the matrix is an identity, ones, or zeros matrix.

Use 5 sample matrices in which their shapes are not lower than  (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [1]:
import numpy as np

In [2]:
matrix_1 = np.array([
                      [1, 4, 7],
                      [2, 5, 8],
                      [3, 6, 9]
            ])

matrix_2 = np.array([
                     [1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]
            ])

matrix_3 = np.array([
                     [1, 5, 9],
                     [3, 5, 7],
                     [7, 4, 3]
            ])

matrix_4 = np.array([
                     [5, 3, 4],
                     [9, 4, 7],
                     [7, 1, 6]
            ])

matrix_5 = np.array([
                     [6, 1, 8],
                     [9, 4, 1],
                     [1, 7, 6]
            ])

In [6]:
def mat_desc(matrix):
  print(matrix)
  if matrix.size > 0:
    square = True if matrix.shape[0] == matrix.shape[1] else False

    print("Shape: ", matrix.shape)
    print("Size: ", matrix.size)
    print("Rank: ", matrix.ndim)
    print("Is the matrix square? ", square)
    print("Is the matrix empty? NO")

    zeroes = not np.any(matrix)
    ones = np.all((matrix == 1))
    rows = len(matrix);
    columns = len(matrix[0]);
    identity = True

    print("Is the matrix zero? ", zeroes)
    print("Is the matrix ones? ", ones)

    for iteration in range(0, rows):
      for number in range(0, columns):
        if(iteration == number and matrix[iteration][number] !=1):
          identity = False
        if(iteration != number and matrix[iteration][number] !=0):
          identity = False

    if identity:
      print("Is the matrix identity? True")
    else:
      print("Is the matrix identity? False")
  
  else:
    print("Shape: N/A")
    print("Size: N/A")
    print("Rank: N/A")
    print("Is the matrix square? N/A")
    print("Is the matrix empty? YES")
    print("Is the matrix zero? N/A")
    print("Is the matrix ones? N/A")
    print("Is the matrix identity? N/A")

In [7]:
mat_desc(matrix_1)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
Shape:  (3, 3)
Size:  9
Rank:  2
Is the matrix square?  True
Is the matrix empty? NO
Is the matrix zero?  False
Is the matrix ones?  False
Is the matrix identity? False


In [ ]:
mat_desc(matrix_2)

In [ ]:
mat_desc(matrix_3)

In [ ]:
mat_desc(matrix_4)

In [ ]:
mat_desc(matrix_5)

# **TASK 2**

Create a function named mat_operations() that takes in two matrices or scalars a input parameters it should:


1.   Display the description of each matrix, if the parameter is a scalar it tells that it is a scalar rather than describing it as a matrix.
2.   Determines if the matrices are viable for operation and returns your own error message if they are not viable.
3. Returns the sum of the matrices.
4. Returns the differen of the matrices.
5. Returns the element-wise multiplication of the matrices.
6. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than  (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.



In [8]:
import numpy as np

In [9]:
matrix_6 = np.array([
                     [7, 4, 2],
                     [9, 4, 5],
                     [1, 6, 7]
                  ])

matrix_7 = np.array([
                     [7, 6, 9],
                     [4, 1, 3],
                     [8, 5, 1]
                  ])

matrix_8 = np.array([
                     [3, 5, 4],
                     [2, 8, 6],
                     [5, 4, 8]
                  ])

matrix_9 = np.array([
                     [4, 5, 6],
                     [9, 7, 2],
                     [6, 3, 1]
                  ])

matrix_10 = np.array([
                      [1, 2, 6],
                      [2, 3, 7],
                      [3, 9, 5]
                  ])

In [14]:
def mat_operations(A, B):
  scalar_One = isinstance(A, (int, float, bytes, complex))
  scalar_Two = isinstance(B, (int, float, bytes, complex))

  matrix_One = isinstance(A, np.ndarray)
  matrix_Two = isinstance(B, np.ndarray)

  print("First Matrix: \n", A)
  print("Is the matrix scalar? \n", scalar_One)

  print("Second Matrix: \n", B)
  print("Is the matrix scalar? \n", scalar_Two)

  if scalar_One == True or scalar_Two == True or matrix_One == True and matrix_Two == True and A.shape == B.shape:
    print("Addition: \n", A+B)
    print("Subtraction: \n", A-B)
    print("Multiplication: \n", A*B)
    print("Division: \n", A/B)
  elif matrix_Two == True and matrix_Two == True and A.shape!= B.shape:
    print("Operation Error. Shapes must be equal")

In [15]:
mat_operations(matrix_6, matrix_7)

First Matrix: 
 [[7 4 2]
 [9 4 5]
 [1 6 7]]
Is the matrix scalar? 
 False
Second Matrix: 
 [[7 6 9]
 [4 1 3]
 [8 5 1]]
Is the matrix scalar? 
 False
Addition: 
 [[14 10 11]
 [13  5  8]
 [ 9 11  8]]
Subtraction: 
 [[ 0 -2 -7]
 [ 5  3  2]
 [-7  1  6]]
Multiplication: 
 [[49 24 18]
 [36  4 15]
 [ 8 30  7]]
Division: 
 [[1.         0.66666667 0.22222222]
 [2.25       4.         1.66666667]
 [0.125      1.2        7.        ]]


In [ ]:
mat_operations(matrix_8, matrix_9)

In [ ]:
mat_operations(matrix_10, matrix_6)