<a href="https://colab.research.google.com/github/TiffanyHizon/Linear_Algebra_58051/blob/main/Laboratory%20Activity%207/LinAlg_58051_Hizon_Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Task 1**

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than  (3,3) . In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [62]:
import numpy as np

In [63]:
matrix_1 = np.array([
                     [1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]
                    ])

matrix_2 = np.array([
                     [9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]
                    ])

matrix_3 = np.array([
                     [5, 1, 2],
                     [2, 4, 1],
                     [2, 1, 2]
                    ])

**Commutative Property**

$$AB \neq BA $$

In [64]:
AB = matrix_1 @ matrix_2
BA = matrix_2 @ matrix_1

In [65]:
print("AB: \n", AB)

AB: 
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [66]:
print("BA: \n", BA)

BA: 
 [[ 90 114 138]
 [ 54  69  84]
 [ 18  24  30]]


In [67]:
np.array_equiv(AB, BA)

False

**Associative Property**

$$(AB)C = A(BC)$$

In [68]:
AB_C = (matrix_1 @ matrix_2) @ matrix_3 

In [69]:
A_BC = matrix_1 @ (matrix_2 @ matrix_3)

In [70]:
print("(AB)C: \n", AB_C)

(AB)C: 
 [[ 234  144  120]
 [ 666  414  345]
 [1098  684  570]]


In [71]:
print("A(BC): \n", A_BC)

A(BC): 
 [[ 234  144  120]
 [ 666  414  345]
 [1098  684  570]]


In [72]:
np.array_equiv(AB_C, A_BC)

True

**Distributive Property**

$$(B+C)\cdot A = B\cdot A + C\cdot A$$

In [73]:
BC_A = (matrix_2 + matrix_3) @ matrix_1
BA_CA = (matrix_2 @ matrix_1) + (matrix_3 @ matrix_1)

In [74]:
print("(B + C)A: \n", BC_A)

(B + C)A: 
 [[113 145 177]
 [ 79 101 123]
 [ 38  49  60]]


In [75]:
print("BA + CA: \n", BA_CA)

BA + CA: 
 [[113 145 177]
 [ 79 101 123]
 [ 38  49  60]]


In [76]:
np.array_equiv(BC_A, BA_CA)

True

**Multiplicative Identity Property**

$$IA = A $$

In [77]:
I = np.eye(3, dtype = int)
IA = I @ matrix_1

In [78]:
print("IA: \n", IA)

IA: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [79]:
print("A: \n", matrix_1)

A: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [80]:
np.array_equiv(IA, matrix_1)

True

**Multiplicative Property of Zero**

$$0A = 0$$

In [81]:
Zero = np.zeros(matrix_1.shape)
OA = Zero @ matrix_1

In [82]:
print("0A: \n", OA)

0A: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [83]:
print("O: \n", Zero)

O: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [84]:
np.array_equiv(Zero, OA)

True

**Multiplication Property 6**

$$A\cdot A^{-1} = I$$

In [85]:
I = np.eye(3, dtype = int)
a_Inv = np.linalg.inv(matrix_3)
Result = matrix_3 @ a_Inv

In [86]:
print("Matrix and Inverse of Matrix: \n", Result.astype(int))
print("I: \n", I)

Matrix and Inverse of Matrix: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
I: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [87]:
np.array_equal(Result.astype(int), I)

True